file cleanup

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -1,49 +1,52 @@
-    !/bin/sh
-    # postinst script for mypackage
-    #
-    # see: dh_installdeb(1)
+#!/bin/sh
+# postinst script for mypackage
+#
+# see: dh_installdeb(1)
 
-    set -e
+set -e
 
-    # summary of how this script can be called:
-    #        * <postinst> `configure' <most-recently-configured-version>
-    #        * <old-postinst> `abort-upgrade' <new version>
-    #        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
-    #          <new-version>
-    #        * <postinst> `abort-remove'
-    #        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
-    #          <failed-install-package> <version> `removing'
-    #          <conflicting-package> <version>
-    # for details, see http://www.debian.org/doc/debian-policy/ or
-    # the debian-policy package
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
 
-    case "$1" in
-        configure)
-            echo "Put your post install script here"
+case "$1" in
+configure)
+echo "Put your post install script here"
 	    #use debconf to get the following:
+	. /usr/share/debconf/confmodule
 		#which interface to use for service, which for uplink
+	    db_get pxe-server-install/uplink-iface
+	    echo $RET
 		#probly that's all for initiall configs but will need reconfigure script
 
-	    #This snippet for downloading:  wget -r -nH --reject index* --cut-dirs=7 http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-$1/current/images/netboot/
-
-        ;;
-
-        abort-upgrade|abort-remove|abort-deconfigure)
-        ;;
-
-        *)
-            echo "postinst called with unknown argument \`$1'" >&2
-            exit 1
-        ;;
-    esac
-
-    # dh_installdeb will replace this with shell code automatically
-    # generated by other debhelper scripts.
 
 
+;;
 
-    #DEBHELPER#
+abort-upgrade|abort-remove|abort-deconfigure)
+;;
 
-    exit 0
+*)
+echo "postinst called with unknown argument \`$1'" >&2
+exit 1
+;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+
+
+#DEBHELPER#
+
+exit 0
 
